services:
  notification-postgres:
    ports: !reset []
    environment:
      POSTGRES_DB: ${NOTIFICATION_DB}
      POSTGRES_USER: ${NOTIFICATION_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_PASSWORD}

  notification-service:
    profiles: !reset []
    ports: !reset []
    env_file: .env.prod
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      POSTGRES_HOST: notification-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${NOTIFICATION_DB}
      POSTGRES_USER: ${NOTIFICATION_USER}
      POSTGRES_PASSWORD: ${NOTIFICATION_PASSWORD}
      MAIL_SENDER: ${MAIL_SENDER}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ACCESS_EXPIRE: ${ACCESS_EXPIRE}
      REFRESH_EXPIRE: ${REFRESH_EXPIRE}
      ACCESS_SECRET_CODE: ${ACCESS_SECRET_CODE}
      REFRESH_SECRET_CODE: ${REFRESH_SECRET_CODE}
      FRONTEND_SPA: ${FRONTEND_SPA}
    restart: unless-stopped