name: CD
on:
  push:
    branches: [main, one-143]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: пуллим с main и запускаем docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          proxy_host: ${{ secrets.PROXY_IP }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          proxy_username: ${{ secrets.SSH_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          script: |
            cd /opt/one_plus_plus/oneplusplus-notification-service
            sudo -u one_plus_plus docker compose -f docker-compose.yml --env-file .env.prod --profile backend down
            sudo -u one_plus_plus git pull origin main
            sudo -u one_plus_plus docker compose -f docker-compose.yml --env-file .env.prod --profile backend up -d --build